"""Extract de novo mutational signatures using SigProfilerExtractor."""

from pathlib import Path
from SigProfilerExtractor import sigpro as sig


def run_sigprofiler(
    input_type: str,
    input_data: str | Path,
    output_dir: str | Path,
    reference_genome: str = "GRCh38",
    context_type: str = "96",
    minimum_signatures: int = 1,
    maximum_signatures: int = 6,
    nmf_replicates: int = 100,
    cpu: int = 1,
):
    """
    Run de novo mutational signature extraction using SigProfilerExtractor.

    Parameters
    ----------
    input_type : str
        Type of input data.

        Common options:
        - "matrix" : mutation count matrix
        - "vcf"    : directory with VCF files

    input_data : str or Path
        Path to the input mutation data.

        If input_type == "matrix":
        ! SigProfilerExtractor expects a tab-separated (.tsv) mutation count matrix!
        
            Expected format:
            - rows: mutation channels
            - columns: samples
            - values: mutation counts

            For SBS96:
                96 trinucleotide mutation contexts × samples

            For ID83:
                83 indel mutation contexts × samples

        If input_type == "vcf":
            Path to a directory containing VCF files.

    output_dir : str or Path
        Directory where SigProfilerExtractor results
        will be saved.

    reference_genome : str
        Reference genome used for mutational opportunity
        correction.

        Common options:
        - "GRCh37"
        - "GRCh38"

    context_type : str
        Mutational context type.

        Common options:
        - "96" : SBS96
        - "83" : ID83

    minimum_signatures : int
        Minimum number of de novo signatures to test.

    maximum_signatures : int
        Maximum number of de novo signatures to test.

    nmf_replicates : int
        Number of NMF replicates performed for each
        tested number of signatures.

    cpu : int
        Number of CPU cores used during computation.

    Notes
    -----
    SigProfilerExtractor performs:
    - de novo signature extraction,
    - stability assessment across NMF replicates,
    - automatic selection of the optimal number
      of signatures.

    Output files generated by SigProfilerExtractor include:
    - extracted signature matrices,
    - exposure matrices,
    - reconstruction statistics,
    - signature plots and visualizations.
    """

    input_data = Path(input_data)
    output_dir = Path(output_dir)

    sig.sigProfilerExtractor(
        input_type=input_type,
        output=str(output_dir),
        input_data=str(input_data),
        reference_genome=reference_genome,
        opportunity_genome=reference_genome,
        context_type=context_type,
        minimum_signatures=minimum_signatures,
        maximum_signatures=maximum_signatures,
        nmf_replicates=nmf_replicates,
        cpu=cpu,
    )


if __name__ == "__main__":

    run_sigprofiler(
        input_type="matrix",
        input_data="data/example_matrix.tsv",
        output_dir="results/sigprofiler/example_run",
        reference_genome="GRCh38",
        context_type="96",
        minimum_signatures=1,
        maximum_signatures=6,
        nmf_replicates=100,
        cpu=1,
    )
